# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lregenar <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/15 20:16:41 by lregenar          #+#    #+#              #
#    Updated: 2019/08/15 20:26:06 by lregenar         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
FILE = display_file.c

.PHONY: all clean fclean

all:
	@gcc -Wall -Wextra -Werror -o $(NAME) $(FILE)

clean:
	@rm -f *.o

fclean:		clean
	@rm -f $(NAME)
